### ISSUE TITLE
Ensure compatibility with IE11

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-integrations-common#12]
As reported in e.g. ckeditor/ckeditor4-vue#75 `integrations-common` package is not compatible with IE11 which breaks the compatibility with IE11 in all integrations where is used now.

It should be fairly easy to change as mentioned in [https://github.com/ckeditor/ckeditor4-vue/issues/75#issuecomment-744313955:](https://github.com/ckeditor/ckeditor4-vue/issues/75#issuecomment-744313955:)

> The fix is quite simple, we need to add additional processing to webpack, similar to what we have in other integrations, e.g. Vue - https://github.com/ckeditor/ckeditor4-vue/blob/master/webpack.config.js#L17-L29 (but as a part of the standard conversion).

**Comment by f1ames** [comment]
> It should be fairly easy...

Or not, because the mentioned config is already there... :thinking: https://github.com/ckeditor/ckeditor4-integrations-common/blob/0bcdfbd1b5a5bff7ac9fb6112fb81516726a3c0c/webpack.config.js#L65-L73

**Comment by sculpt0r** [comment]
#15 Seems to fix this.  
Transpiled version was published, but due to `module` in `package.json` pointing to `src` instead of `dist` - other integrations used not transpiled version.
