### ISSUE TITLE
Add scripts for building and publishing package

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-integrations-common#3]
To be able to use the package in our integration repos we need to release it first, so we have to add the scripts for building and releasing to npm.

**Comment by f1ames** [comment]
It would be perfect to use the same approach/workflow we have in integrations, so just running `npm version` which run tests, creates dist folder (if is needed), creates tag and pushes changes to upstream. See e.g. https://github.com/ckeditor/ckeditor4-angular/blob/7de8b0d48c975550c29c0d2bf0eeb810847410d0/package.json#L16-L18.

**Comment by Dumluregn** [comment]
The building part was done in #2, so now we only need publishing scripts.

**Comment by jacekbogdanski** [comment]
It's already covered in https://github.com/ckeditor/ckeditor4-integrations-common/blob/master/package.json#L11-L13

@Dumluregn what do you mean about publishing scripts?

**Comment by Dumluregn** [comment]
Ooook, I what I meant was that in ckeditor4-angular we have a [separate `publish` script](https://github.com/ckeditor/ckeditor4-angular/blob/master/package.json#L15), but it's basically an alias for `npm publish` 😅 So there is no real need to implement this here. Hence, I'm closing the issue as covered in #2.
