### ISSUE TITLE
Page layout breaks if editor is maximized and you navigate back in browser

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-integrations-common#8]
This issue is already reported in both Angular and Vue integrations, probably exists also in React one, which makes fixing it a good candidate for the next common util.

Originally reported in Angular:
https://github.com/ckeditor/ckeditor4-angular/issues/141

Checked and confirmed in Vue:
https://github.com/ckeditor/ckeditor4-vue/issues/64

**Comment by f1ames** [comment]
This one is generally related to how maximize works - it is an issue with every SPA application basically. So I think:

1.  There should be a way API to "demaximize" editor so custom integrations could use to fix this issue (not sure it will require any changes in CKEditor 4 itself or calling `maximize` second time does the job).
2.  Official integrations should have built-in mechanism using the above so it works out of the box.

**Comment by f1ames** [comment]
Ok, I see [`maximize` command works both ways](https://github.com/ckeditor/ckeditor4/blob/a3b457960f32574ee50d8e1956999e42349ffd23/plugins/maximize/plugin.js#L206-L207) :+1:

**Comment by f1ames** [comment]
We decided to try to cover it in CKEditor 4 itself. In an unlikely event that it will not be possible we could try to cover it here.
