### ISSUE TITLE
Document the repo utilities

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-integrations-common#9]
It would be good to add a short, one sentence long description what is the purpose of each of the functions in this repo. As it is mostly internal stuff, I think that adding the comments in code will be totally enough.

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4-integrations-common/commit/8131ac8f8b11dcab2f001c15d637455a42995f22
